version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/db.Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app.Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
volumes:
  db-store: