name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: "go test ./..."
	    - run: "go vet ./..."
